const products = [
    {   id: 1,
        name: 'Футболка UZcotton мужская',
        price: 1051,
        price_with_sale: 522,
        color: 'Белый',
        size: '56',
        store: 'Коледино WB',
        seller: 'OOO Вайлдберриз'},
    {   id: 2,
        name: 'Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe',
        price: 11500,
        price_with_sale: 10500,
        color: 'прозрачный',
        size: '56',
        store: 'Коледино WB',
        seller: 'OOO Мегапрофстиль'},
    {   id: 3,
        name: 'Карандаши цветные Faber-Castell "Замок", набор 24 цвета, заточенные, шестигранные, Faber-Castell ',
        price: 475,
        price_with_sale: 247,
        store: 'Коледино WB',
        seller: 'OOO Вайлдберриз'}
];